# Super Shop Configuration
# A decentralized player-driven trading system

# Database Configuration
database:
  # Database type: sqlite or mysql
  type: sqlite
  # MySQL settings (only used if type is mysql)
  host: localhost
  port: 3306
  database: supershop
  username: root
  password: ""

# Shop Settings
shop:
  # Maximum number of shops per player (-1 for unlimited)
  max-shops-per-player: 1
  # Maximum number of items per shop
  max-items-per-shop: 54
  # Allow trading between different worlds
  allow-cross-world-trading: true
  # Require permission to create shops
  require-permission-to-create: false



# Search Book Settings
search-book:
  # Enable search book functionality
  enabled: true
  # Maximum search results to display
  max-results: 50
  # Maximum search radius in blocks
  search-radius: 10000
  # Require permission to use search book
  require-permission: false
  # Cooldown between searches in seconds
  cooldown-seconds: 5