name: supershop
version: '1.1.0'
main: me.nouridin.supershop.supershop
api-version: '1.21'
author: Nouridin
description: A decentralized player-driven trading system for servers
website: https://modrinth.com/plugin/super-shop
depend:

commands:
  shop:
    description: Main shop command
    usage: /shop <create|remove|list|info|give|stats|reload|help>
    aliases: [shops, tradingchest]
  searchbook:
    description: Search for items in player shops
    usage: /searchbook <item name>
    aliases: [search, finditem]

permissions:
  supershop.*:
    description: All WL Super Shop permissions
    children:
      supershop.create: true
      supershop.searchbook: true
      supershop.give: true
      supershop.stats: true
      supershop.reload: true
      supershop.admin: true
      supershop.unlimited: true
      supershop.nocooldown: true
      supershop.teleport: true
  supershop.create:
    description: Permission to create shops
    default: true
  supershop.searchbook:
    description: Permission to use search book
    default: true
  supershop.give:
    description: Permission to give search books to players
    default: op
  supershop.stats:
    description: Permission to view shop statistics
    default: op
  supershop.reload:
    description: Permission to reload plugin configuration
    default: op
  supershop.admin:
    description: Admin permission to manage all shops
    default: op
  supershop.unlimited:
    description: Permission to bypass shop limits
    default: op
  supershop.nocooldown:
    description: Permission to bypass search cooldowns
    default: op
  supershop.teleport:
    description: Permission to teleport to shops from search results
    default: op
  supershop.update.notify:
    description: Receive Plugin updates
    default: op